### PR TITLE
Add visibleFrame to Screen api

### PR DESCRIPTION
**Pull request by shayne**
In order to correctly position a Modal you need the (potentially) negative x-coordinate given by the Screen's visibleFrame.

### CODE REVIEW

**Comment by kasper** [comment]
Interesting! Would you be able to give an example when you would need this instead of the origin adjusted `visibleFrameInRectangle`?

**Comment by shayne** [comment]
Sure! I ran into an issue when displaying a modal centered on the current screen. https://github.com/shayne/phonad/blob/master/phoenix.js#L119

**Comment by kasper** [comment]
@shayne Hmm, this shouldn’t be needed.

```javascript
var frame = Screen.mainScreen().visibleFrameInRectangle();

// Centered modal
var modal = new Modal();
modal.message = 'Message';
modal.origin = { x: (frame.width / 2) - (modal.frame().width / 2),
                 y: (frame.height / 2) - (modal.frame().height / 2) };
modal.show();
```

Am I missing something? I’m hesitant about merging this to avoid confusion against the origin corrected frames.

**Comment by jasonm23** [comment]
I think leaving the burden of positioning on the JS side is probably a better idea.

**Comment by shayne** [comment]
It was my experience that this method centered the modal on the primary
screen. Try centering the modal on a secondary screen. I had to use
visibleFrame for this to work.

On Fri, Nov 20, 2015 at 4:17 AM, Kasper Hirvikoski <notifications@github.com

**Comment by kasper** [comment]
@shayne Only the y-coordinate is adjusted. I’m currently abroad, so I do not have access to my secondary screen, but I successfully use and have used this calculation to centre windows on secondary screens: https://gist.github.com/kasper/b7c2a1596a90246c9ccd#file-phoenix-js-L18 

As such, this should work:

```javascript
var frame = Screen.mainScreen().visibleFrameInRectangle();

// Centered modal
var modal = new Modal();
modal.message = 'Message';
modal.origin = { x: frame.x + ((frame.width - modal.frame().width) / 2),
                 y: frame.y + ((frame.height - modal.frame().height) / 2) };
modal.show();
```

Still looks easier than your way. :) I’m just hesitant about making this API confusing with multiple available frames and agree with @jasonm23 that the burden to calculate correctly should be on the JavaScript side.

**Comment by shayne** [comment]
Aha... My secondary screen sits below my primary (MacBook Pro < Thunderbolt
Display)

On Mon, Nov 23, 2015 at 5:12 AM, Kasper Hirvikoski <notifications@github.com

**Comment by shayne** [comment]
I assumed @jasonm23 was inferring that we keep the frame denormalized and
provide the JS end the the precise frame.

**Comment by kasper** [comment]
@shayne Ah, perhaps. I haven’t changed this behaviour, it has been this way from the beginning. I was puzzled by the actual reason first, but the reason is to make it easier and more straightforward to count the y-position. At least this is how I understand it. Especially as a secondary screen can be positioned in any corner, lower or higher than the main screen — as you just noticed. So I think it’s reasonable.

**Comment by kasper** [comment]
I’ll close this for now, but this is duly noted.

**Pull request closed without merging**
