### PR TITLE
"-cl" is not valid with some shells (e.g. Fish)

### PR DESCRIPTION
**Pull request by shayne**
Pass "-l" for login and "-c" for command, separately

### CODE REVIEW

**Comment by jasonm23** [comment]
Good catch

**Comment by kasper** [comment]
@shayne Thanks! :+1:

@jasonm23 In the future, we should probably enforce the Contribution guidelines a bit more. I would like all pull requests that fix bugs or add new features to document the changes not only to the API, but Changelog as well (4.). This will make it easier to follow the changes on the master branch and not miss any potential Changelog notes. These should follow the existing categories and format for Changelog notes.

**Comment by jasonm23** [comment]
Noted.  This should be added to the Changelog for sure, my apologies.

**Comment by kasper** [comment]
@jasonm23 No need to apologise! I’ve let this past a couple of times myself. It’s good do discuss these along the way. :)

**Comment by jasonm23** [comment]
We can do adv. filtering on github issues. So we can collect PR/Issues closed within a time range btw.

No need to worry about forgetting them.

**Comment by kasper** [comment]
@jasonm23 Sure, I’m just a very careful and organised person. As you might have noticed. :)

**Comment by jasonm23** [comment]
: ) me too, in theory

**Pull request merged**
