### PR TITLE
Fix #167, #169

### LINKED ISSUE #167: Phoenix fails to launch after some time
- Version: 2.5 (59)
- macOS: 10.12.3 (16D32)

Sometimes, after restarting Phoenix, it won't be responsive. Hovering over the icon in the menu bar results in the rainbow spinner. The following line is logged in Console:

```
default	16:44:45.507129 -0800	Phoenix	subsystem: com.apple.SkyLight, category: default, enable_level: 0, persist_level: 0, default_ttl: 7, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
```

Followed by a dozen or so of these lines:

```
default	16:44:45.514018 -0800	Phoenix	Local database thinks system build version is <private>, but the OS really is <private>.
```

I have to reboot in order for Phoenix to work properly again. Any idea what it could be?

### PR DESCRIPTION
**Pull request by metakirby5**
- [x] Updated related documentations
- [x] Added the change to the Changelog

Fix issue where `PHShebangPreprocessor` blocks due to race conditions.

[Read](http://stackoverflow.com/a/39281558) a related StackOverflow answer.

### CODE REVIEW

**Comment by kasper** [comment]
@metakirby5 Thanks for the contribution! Seems solid, but I’ll verify this as soon as I have some time.

**Comment by metakirby5** [comment]
Wondering if we can get this merged in, as it's been outstanding for quite awhile.

**Comment by kasper** [comment]
Yes, I’ve been just extremely busy for the past couple months. I will get back to these, promise!

**Comment by kasper** [comment]
Thanks! I’m sorry for the (extremely) long wait! Merged this in #198.

**Pull request merged**
