### PR TITLE
Improve debug capabilities in the Safari context by listing of configuration file(s) in the developer tools sidebar

### PR DESCRIPTION
**Pull request by varp**
- [X] Updated related documentations
- [X] Added the change to the Changelog

### CODE REVIEW

**Comment by kasper** [comment]
Oh, nice one! Will review and test this once I have time.

**Comment by mafredri** [comment]
@varp, super nice! I had to make some tweaks to my typescript config (uses webpack) to get the sourcemaps included, but after that, worked perfectly. I did have to use the debug build of Phoenix though, when I build it with prod settings it doesn't show up as a JSContext in Safari.

**Comment by kasper** [comment]
@mafredri Yes, unfortunately Apple has restricted this.

**Review by kasper — APPROVED** [review]

**Comment by kasper** [comment]
Thank you! Seems to work nicely!

**Comment by varp** [comment]
Was glad to be a part of!

**Pull request merged**
